markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "Peng Meng"

author: "Peng Meng"
atom-baseurl: "http://pengmeng.me"
disqus: "pengmeng"

navigations:
    - title: Archive
      class: fa fa-list-ul
      href: /archive.html
    - title: Tags
      class: fa fa-tags
      href: /tags.html
    - title: About
      class: fa fa-user
      href: /about.html
    - title: Resume
      class: fa fa-file-text-o
      href: /resume.html
    - title: Links
      class: fa fa-link
      href: /links.html
    - title: Subscribe
      class: fa fa-rss
      href: /atom.xml

